name: First WorkFlow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: |
              echo "HELLO WORLD !!!"
              echo "GOOD TO MEET YOU"
      - name: Print Goodbye
        run: |
              echo "DONE"
              echo "GOOD BYE !!"
